version: '3.9'

services:
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: django-celery-demo
    command: /start
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - redis

  
  nginx:
    build: ./nginx
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - web


  redis:
    image: redis:6-alpine


  celery_worker:
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: /start-celeryworker
    container_name: celery-worker
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
volumes:
  static_volume:


  