# Generated by Django 4.0.5 on 2022-06-29 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Student',
            new_name='Questions',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='student_id',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='student_name',
            new_name='question_name',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
