# Generated by Django 4.0.5 on 2022-06-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userclass_rename_student_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
