# Generated by Django 4.1.7 on 2023-06-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_testcases_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcases',
            name='input',
        ),
        migrations.RemoveField(
            model_name='testcases',
            name='output',
        ),
        migrations.AddField(
            model_name='testcases',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
