# Generated by Django 4.1.7 on 2023-06-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_remove_testcases_input_remove_testcases_output_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcases',
            name='data',
        ),
        migrations.AddField(
            model_name='testcases',
            name='answer_file',
            field=models.FileField(default=None, upload_to='C:\\Users\\harsh\\Desktop\\oj\\oj/static'),
        ),
        migrations.AddField(
            model_name='testcases',
            name='input_file',
            field=models.FileField(default=None, upload_to='C:\\Users\\harsh\\Desktop\\oj\\oj/static'),
        ),
    ]
