# Generated by Django 4.1.7 on 2023-06-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_solution_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='id',
        ),
        migrations.AddField(
            model_name='solution',
            name='solution_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
