# Generated by Django 4.1.7 on 2023-06-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_remove_solution_id_solution_solution_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='solution_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
