# Generated by Django 4.1.7 on 2023-06-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0007_alter_solution_solution_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='solution_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
