# Generated by Django 4.2.3 on 2023-07-07 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="last_accepted",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 14, 16, 56, 2, 571571)
            ),
        ),
    ]
