# Generated by Django 4.1.7 on 2023-07-03 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='contest_date',
        ),
    ]
