# Generated by Django 4.2.3 on 2023-07-08 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contests", "0002_alter_score_last_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="is_active",
            field=models.CharField(default="inactive", max_length=20),
        ),
        migrations.AlterField(
            model_name="score",
            name="last_accepted",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 15, 17, 22, 39, 821161)
            ),
        ),
    ]
