# Generated by Django 4.1.7 on 2023-07-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_question_points_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='penalties',
            field=models.IntegerField(default=0),
        ),
    ]
