# Generated by Django 4.2.3 on 2023-07-12 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contests", "0003_alter_contest_is_active_alter_score_last_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="last_accepted",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 19, 9, 38, 15, 503197)
            ),
        ),
    ]
