# Generated by Django 4.1.7 on 2023-07-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_score_penalties'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
