# Generated by Django 4.1.7 on 2023-07-04 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='last_accepted',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 11, 11, 53, 41, 524957, tzinfo=datetime.timezone.utc)),
        ),
    ]
