# Generated by Django 4.2.3 on 2023-07-15 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contests", "0006_alter_score_last_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="last_accepted",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(
                    2023, 7, 25, 15, 45, 58, 164634, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
