# Generated by Django 4.2.3 on 2023-07-17 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contests", "0007_alter_score_last_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="last_accepted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 27, 12, 28, 26, 847434, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
