# Generated by Django 4.1.7 on 2023-07-06 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0011_alter_contest_end_time_alter_contest_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='last_accepted',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 9, 22, 21, 817289)),
        ),
    ]
