# Generated by Django 4.1.7 on 2023-07-06 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0013_alter_contest_end_time_alter_contest_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='last_accepted',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 11, 25, 31, 649347)),
        ),
    ]
