# Generated by Django 4.2.3 on 2023-07-18 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0031_alter_score_last_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='last_accepted',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 28, 7, 39, 38, 849831, tzinfo=datetime.timezone.utc)),
        ),
    ]
